michael = User.create(name:"Michael", email:"mdo5004@psu.edu", password:"password",role:2)
rachel = User.create(name:"Rachel", email:"rachel.v.oconnell@gmail.com", password:"password",role:0)
michael.notes.create(content:"Hey-o, I'm making an app with Pundit", visible_to: "Rachel")
rachel.notes.create(content:"That's nice. I don't know what that is.", visible_to:"Michael")
michael.notes.create(content:"Me neither", visible_to: "Rachel")